# Generated by Django 5.2.1 on 2025-05-19 04:22

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0004_alter_like_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storyimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
